/**
 * Gina Framework — Explicit exports
 *
 * Type declarations for `require('gina/gna')`.
 * Provides named imports for all global helpers, enabling IDE navigation
 * and static analysis without relying on global scope injection.
 *
 * AUTO-GENERATED by script/generate_gna_types.js — do not edit by hand.
 * Source of truth: JSDoc on core/gna.js (per-global) and globals.d.ts.
 * Run `npm run types:gen` after adding or removing a global export.
 *
 * Usage:
 *   const { getContext, _, onCompleteCall, uuid } = require('gina/gna');
 */

import type { UuidFunction } from './globals';
import type { SuperControllerConstructor, EntitySuperConstructor } from './index';

interface GinaExports {
    // Context helpers
    /** Store a value in the framework context registry under `name`. */
    setContext: typeof globalThis.setContext;
    /** Read a value from the framework context registry. */
    getContext: typeof globalThis.getContext;
    /** Merge an additional contexts object into the current registry. */
    joinContext: typeof globalThis.joinContext;
    /** Rebuild the context registry from `GINA_*` environment variables and the current project manifest. */
    resetContext: typeof globalThis.resetContext;
    getConfig: typeof globalThis.getConfig;
    /** Load a bundle library by name and return an instantiated class. */
    getLib: typeof globalThis.getLib;
    /** Replace `${key}` tokens in a string or object using a dictionary. */
    whisper: typeof globalThis.whisper;
    /** Define a read-only constant on the global object. */
    define: typeof globalThis.define;
    /** List all `GINA_*` and `USER_*` constants currently defined on the global object. */
    getDefined: typeof globalThis.getDefined;

    // Platform helper
    /** Check whether the current platform is Windows. */
    isWin32: typeof globalThis.isWin32;

    // Path helpers
    /** Normalise a path string or construct a PathObject for a directory. */
    _: typeof globalThis._;
    /** Register a named path in the context paths registry. */
    setPath: typeof globalThis.setPath;
    /** Read a named path from the context paths registry. */
    getPath: typeof globalThis.getPath;
    /** Replace the whole paths registry in one call. */
    setPaths: typeof globalThis.setPaths;
    /** Read the full paths registry. */
    getPaths: typeof globalThis.getPaths;
    /** Promisify an `.onComplete(cb)` EventEmitter, as returned by `Shell::run` or the `run()` global. */
    onCompleteCall: typeof globalThis.onCompleteCall;

    // Model helpers
    /** Load a bundle model and return its entity map. */
    getModel: typeof globalThis.getModel;
    /** Instantiate a bundle model entity with an optional connection. */
    getModelEntity: typeof globalThis.getModelEntity;

    // JSON helper
    /**
     * Read a JSON file, strip `//` and `/* ... *\/` comments, tolerate trailing commas, and
     * return the parsed object.
     */
    requireJSON: typeof globalThis.requireJSON;

    // Data helpers
    /** URL-encode a string per RFC 5987 (adds `!` handling and `*` → `%2A`). */
    encodeRFC5987ValueChars: typeof globalThis.encodeRFC5987ValueChars;
    /** Parse a form/body string (`application/x-www-form-urlencoded` or JSON) into a nested object. */
    formatDataFromString: typeof globalThis.formatDataFromString;

    // Text helper
    /** Legacy one-arg translation alias. */
    __: typeof globalThis.__;

    // Console helper
    /** Write arguments to `process.stdout` followed by a newline. */
    log: typeof globalThis.log;

    // Task helper
    /**
     * Run a shell command via `child_process.spawn` with a Promise-friendly `onComplete` /
     * `onData` EventEmitter API.
     */
    run: typeof globalThis.run;

    // Env helpers
    /** Resolve the user's home directory (`USERPROFILE` on win32, `HOME` elsewhere). */
    getUserHome: typeof globalThis.getUserHome;
    /** Read a `GINA_*` / `VENDOR_*` / `USER_*` env var from `process.gina`. */
    getEnvVar: typeof globalThis.getEnvVar;
    /** Return the entire `process.gina` env-var map. */
    getEnvVars: typeof globalThis.getEnvVars;
    /** Set a `GINA_*` / `VENDOR_*` / `USER_*` env var in `process.gina`. */
    setEnvVar: typeof globalThis.setEnvVar;
    /** List keys that were marked protected via `setEnvVar(..., true)`. */
    getProtected: typeof globalThis.getProtected;
    /**
     * Scan `process.argv` for `--key=value` flags, promote them to `process.gina` env vars, then
     * strip them from `argv`.
     */
    filterArgs: typeof globalThis.filterArgs;
    /**
     * Import `GINA_*` / `VENDOR_*` / `USER_*` keys from `process.env` into the framework
     * environment (`process.gina`).
     */
    importEnvVars: typeof globalThis.importEnvVars;
    /**
     * Resolve the log directory — `GINA_LOGDIR` / `LOGDIR` / prefix `var/log` with fallback to
     * `~/.gina/log`.
     */
    getLogDir: typeof globalThis.getLogDir;
    /** Resolve the run/lock directory — prefix `var/lock` with fallback to `~/.gina/run`. */
    getRunDir: typeof globalThis.getRunDir;
    /** Resolve the tmp directory — `GINA_TMPDIR` / `os.tmpdir()` with fallback to prefix `var/tmp`. */
    getTmpDir: typeof globalThis.getTmpDir;
    /**
     * Read the saved startup argv for a given bundle@project — used by `gina bundle:restart` to
     * re-issue the exact same start command.
     */
    getBundleStartingArgv: typeof globalThis.getBundleStartingArgv;
    /** Read a vendor config loaded via `setVendorsConfig`. */
    getVendorsConfig: typeof globalThis.getVendorsConfig;
    /** Load every `*.json` file in `dir` as a vendor config keyed by filename. */
    setVendorsConfig: typeof globalThis.setVendorsConfig;
    /** Bulk-register an object of env vars as `USER_*` defaults via `define`. */
    defineDefault: typeof globalThis.defineDefault;
    /** Convert a user-facing timeout ("30s", "500ms", "1m", "2h", `number`, `false`) to milliseconds. */
    parseTimeout: typeof globalThis.parseTimeout;
    /** Framework's deep-merge helper — loaded via `utils/helper.js` and also available as `lib.merge`. */
    merge: typeof globalThis.merge;

    // ApiError
    ApiError: typeof globalThis.ApiError;

    // Classes — the CONSTRUCTOR VALUES live on this barrel (root gna.js),
    // not on the main entry, whose declarations are type-only.
    SuperController: SuperControllerConstructor;
    EntitySuper: EntitySuperConstructor;

    // uuid
    uuid: UuidFunction;
}

declare const ginaExports: GinaExports;
export = ginaExports;
