/**
 * Gina Framework — Explicit exports
 *
 * Type declarations for `require('gina/gna')`.
 * Provides named imports for all global helpers, enabling IDE navigation
 * and static analysis without relying on global scope injection.
 *
 * AUTO-GENERATED by script/generate_gna_types.js — do not edit by hand.
 * Source of truth: JSDoc on core/gna.js (per-global) and globals.d.ts.
 * Run `npm run types:gen` after adding or removing a global export.
 *
 * Usage:
 *   const { getContext, _, onCompleteCall, uuid } = require('gina/gna');
 */

import type { UuidFunction } from './globals';
import type { SuperController, EntitySuper } from './index';

interface GinaExports {
    // Context helpers
    /** Store a value in the framework context registry under `name`. */
    setContext: typeof globalThis.setContext;
    /** Read a value from the framework context registry. */
    getContext: typeof globalThis.getContext;
    /**
     * Merge an additional contexts object into the current registry.
     *
     * @param context - Partial contexts to merge in
     */
    joinContext: (context: object) => void;
    /** Rebuild the context registry from `GINA_*` environment variables and the current project manifest. */
    resetContext: typeof globalThis.resetContext;
    getConfig: typeof globalThis.getConfig;
    /** Load a bundle library by name and return an instantiated class. */
    getLib: typeof globalThis.getLib;
    /** Replace `${key}` tokens in a string or object using a dictionary. */
    whisper: typeof globalThis.whisper;
    /** Define a read-only constant on the global object. */
    define: typeof globalThis.define;
    /** List all `GINA_*` and `USER_*` constants currently defined on the global object. */
    getDefined: typeof globalThis.getDefined;

    // Platform helper
    /** Check whether the current platform is Windows. */
    isWin32: typeof globalThis.isWin32;

    // Path helpers
    /** Normalise a path string or construct a PathObject for a directory. */
    _: typeof globalThis._;
    /** Register a named path in the context paths registry. */
    setPath: typeof globalThis.setPath;
    /** Read a named path from the context paths registry. */
    getPath: typeof globalThis.getPath;
    /** Replace the whole paths registry in one call. */
    setPaths: typeof globalThis.setPaths;
    /** Read the full paths registry. */
    getPaths: typeof globalThis.getPaths;
    /** Promisify an `.onComplete(cb)` EventEmitter from PathObject / Shell ops. */
    onCompleteCall: typeof globalThis.onCompleteCall;

    // Model helpers
    /** Load a bundle model and return its entity map. */
    getModel: typeof globalThis.getModel;
    /** Instantiate a bundle model entity with an optional connection. */
    getModelEntity: typeof globalThis.getModelEntity;

    // JSON helper
    /**
     * Read a JSON file, strip `//` and `/* ... *\/` comments, tolerate trailing commas, and
     * return the parsed object.
     */
    requireJSON: typeof globalThis.requireJSON;

    // Data helpers
    /**
     * URL-encode a string per RFC 5987 (adds `!` handling and `*` → `%2A`).
     *
     * @param str - Raw string
     * @returns RFC-5987-encoded value
     */
    encodeRFC5987ValueChars: (str: string) => string;
    /**
     * Parse a form/body string (`application/x-www-form-urlencoded` or JSON) into a nested
     * object. Recognises PHP-style `foo[bar][0]` keys.
     *
     * @param bodyStr - Body string; objects are `JSON.stringify`-ed first
     * @returns Parsed object
     */
    formatDataFromString: (bodyStr: string | object) => object;

    // Text helper
    /** i18n placeholder — currently a no-op, preserved for forward compatibility. */
    __: typeof globalThis.__;

    // Console helper
    /**
     * Write arguments to `process.stdout` followed by a newline. Objects are JSON-stringified
     * with tab indentation.
     *
     * @param args - Values to print
     */
    log: (...args: any[]) => void;

    // Task helper
    /**
     * Run a shell command via `child_process.spawn` with a Promise-friendly `onComplete` /
     * `onData` EventEmitter API.
     */
    run: typeof globalThis.run;

    // Env helpers
    /** Resolve the user's home directory (`USERPROFILE` on win32, `HOME` elsewhere). */
    getUserHome: typeof globalThis.getUserHome;
    /** Read a `GINA_*` / `VENDOR_*` / `USER_*` env var from `process.gina`. */
    getEnvVar: typeof globalThis.getEnvVar;
    /** Return the entire `process.gina` env-var map. */
    getEnvVars: typeof globalThis.getEnvVars;
    /** Set a `GINA_*` / `VENDOR_*` / `USER_*` env var in `process.gina`. */
    setEnvVar: typeof globalThis.setEnvVar;
    /**
     * List keys that were marked protected via `setEnvVar(..., true)`.
     *
     * @returns Array of protected env-var names
     */
    getProtected: () => string[];
    /**
     * Scan `process.argv` for `--key=value` flags, promote them to `process.gina` env vars, then
     * strip them from `argv`. Runs once during CLI bootstrap.
     */
    filterArgs: () => void;
    /**
     * Resolve the log directory — `GINA_LOGDIR` / `LOGDIR` / prefix `var/log` with fallback to
     * `~/.gina/log`.
     */
    getLogDir: typeof globalThis.getLogDir;
    /** Resolve the run/lock directory — prefix `var/lock` with fallback to `~/.gina/run`. */
    getRunDir: typeof globalThis.getRunDir;
    /** Resolve the tmp directory — `GINA_TMPDIR` / `os.tmpdir()` with fallback to prefix `var/tmp`. */
    getTmpDir: typeof globalThis.getTmpDir;
    /**
     * Read the saved startup argv for a given bundle@project — used by `gina bundle:restart` to
     * re-issue the exact same start command.
     *
     * @param bundle - Bundle name
     * @param project - Project name
     * @returns Space-separated argv, or `null` when no file exists
     */
    getBundleStartingArgv: (bundle: string, project: string) => string | null;
    /**
     * Read a vendor config loaded via `setVendorsConfig`.
     *
     * @param vendor - Vendor key; omit for the whole map
     * @returns Vendor config, or full map
     */
    getVendorsConfig: (vendor?: string) => object | undefined;
    /**
     * Load every `*.json` file in `dir` as a vendor config keyed by filename.
     *
     * @param dir - Directory containing vendor config files
     */
    setVendorsConfig: (dir: string) => void;
    /**
     * Bulk-register an object of env vars as `USER_*` defaults via `define`.
     *
     * @param obj - Map of `name → value`
     */
    defineDefault: (obj: object) => void;
    /** Convert a user-facing timeout ("30s", "500ms", "1m", "2h", `number`, `false`) to milliseconds. */
    parseTimeout: typeof globalThis.parseTimeout;
    /**
     * Framework's deep-merge helper — loaded via `utils/helper.js` and also available as
     * `lib.merge`.
     *
     * @param target - Destination object (mutated)
     * @param source - Source object
     * @param force - Overwrite primitives when both sides define them
     * @returns The merged target
     */
    merge: (target: object, source: object, force?: boolean) => object;

    // ApiError
    ApiError: typeof globalThis.ApiError;

    // Classes
    SuperController: typeof SuperController;
    EntitySuper: typeof EntitySuper;

    // uuid
    uuid: UuidFunction;
}

declare const ginaExports: GinaExports;
export = ginaExports;
