#!/usr/bin/env node

/*
 * This file is part of the gina package.
 * Copyright (c) 2009-2026 Rhinostone <contact@gina.io>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * Pre-pack leak check.
 *
 * Runs as the `prepack` npm lifecycle hook. Before the tarball is assembled,
 * this script re-runs `npm pack --dry-run --json --ignore-scripts` and fails
 * the publish if the pack listing is dirty on either of two axes:
 *
 *   1. Path-level: any local-tool configuration file or directory.
 *   2. Content-level (two sub-axes per scanned text file):
 *      (a) Private-token pattern (phone, private email, private address,
 *          private domain). The co-author's legal name is allowed in
 *          authoring/contributing files (README, AUTHORS, GOVERNANCE,
 *          CONTRIBUTING, package.json contributors, scaffolding template,
 *          framework AUTHORS, framework plugin package.json authors) —
 *          see `ATTRIBUTION_PATHS` in `_load_private_tokens.js`.
 *      (b) AI-attribution leak (#R5, 2026-05-19): file content embedding
 *          local-tool path literals (`CLAUDE.md`, `.claude/...`),
 *          attribution footers (Co-Authored-By Claude/Anthropic, Generated
 *          by Claude), AI-tool URLs (claude.ai, claude.com/claude-code).
 *          Vendor-functionality references (protocol identifiers, vendor
 *          SDK names, env-var names) are stripped before the check so the
 *          AI connector code and provider tables don't false-positive.
 *
 * Plus a third gate that fires BEFORE the scan starts:
 *
 *   3. Stable-publish gate: if `npm_command=publish` AND `npm_config_tag=latest`
 *      (i.e. `npm publish` without `--tag alpha`) AND the maintainer-local
 *      sidecar `script/.private-tokens.json` is missing, fail closed before
 *      the scan starts. This prevents a fresh-clone or restored-machine
 *      stable publish from silently shipping with content-level scanning
 *      disabled. Alpha publish, npm pack, and contributor `npm install`
 *      flows continue to no-op silently — path-level scanning still runs.
 *      See llms.txt §92 for the rationale.
 *
 * `--ignore-scripts` prevents recursion into the `prepare` script (which
 * would otherwise re-invoke `prepare_version.js` and commit a "Prerelease
 * update").
 *
 * Exit codes:
 *   0  — pack listing and contents are clean
 *   1  — leakage detected, check itself errored (fail closed), OR
 *        stable-publish gate triggered (sidecar missing on `npm publish`
 *        without `--tag alpha`)
 */

var execSync = require('child_process').execSync;
var fs       = require('fs');
var path     = require('path');

var loadPrivateTokens = require('./_load_private_tokens');

var PATH_PATTERN = /(^|\/)(CLAUDE\.md|\.claude[a-z]*)/i;

// Private tokens that must not appear in published tarball contents.
// Patterns load from `script/.private-tokens.json` (gitignored,
// maintainer-local). If the sidecar is absent, content-level scanning
// is a no-op; path-level scanning still runs unchanged. The attribution
// allowlist (`ATTRIBUTION_PATHS`) lives in `_load_private_tokens.js`
// alongside the loader — both shipping scanners use the default so the
// regex stays in one place.
var CONTENT_TOKENS = loadPrivateTokens();

// AI-attribution leak (#R5) — content-level pattern set matching the
// global HARD RULE forbidden surface. Catches the 0.3.15 leak shape
// where a tarball file's NAME was clean but its CONTENT embedded
// forbidden strings (the gitignored sidecar `script/.local-sync-targets.json`
// listed `CLAUDE.md` + `.claude/conventions.md` as literal paths; the
// PATH_PATTERN scan above missed it because the sidecar's own filename
// is neutral). Pattern covers: bare `CLAUDE.md` literal, `.claude*`
// directory/file paths, AI-tool URLs (claude.ai, claude.com/claude-code),
// attribution footers (Co-Authored-By Claude/Anthropic, Generated by
// Claude, noreply@anthropic.com, 🤖-prefixed Claude mentions).
var ATTRIBUTION_LEAK_RE = /\bCLAUDE\.md\b|\.claude[a-z]*|claude\.ai|claude\.com\/claude-code|Co-Authored-By:?\s*[^\n]{0,30}(?:Claude|Anthropic)|noreply@anthropic\.com|Generated (?:by|with)\s+\[?Claude|🤖[^\n]{0,30}Claude/i;

// Vendor-functionality references — stripped from content BEFORE the
// leak check so the AI connector and provider tables don't false-
// positive on legitimate vendor mentions. Matches the "Allowed
// exceptions — product functionality (not attribution)" block in the
// global HARD RULE: AI-connector protocol identifiers, vendor SDK
// package names, canonical env-var names. Any token here is replaced
// with empty string in a one-shot copy of the content before
// ATTRIBUTION_LEAK_RE.test() runs.
var ATTRIBUTION_EXCEPTION_RE = /anthropic:\/\/|openai:\/\/|deepseek:\/\/|qwen:\/\/|groq:\/\/|mistral:\/\/|gemini:\/\/|xai:\/\/|perplexity:\/\/|ollama:\/\/|@anthropic-ai\/sdk|ANTHROPIC_API_KEY|OPENAI_API_KEY/gi;

// Heuristic: only read files that are likely text. Saves time on binary
// assets (images, compiled JARs, compressed .br/.gz) and prevents
// pattern matches from random byte sequences.
var TEXT_EXT = /\.(md|txt|json|js|mjs|cjs|ts|tsx|jsx|html|htm|css|sass|scss|less|sh|bash|zsh|yaml|yml|xml|svg|csv|d\.ts|mapping|conf|ini|toml|env|template)$/i;
var TEXT_BASENAME = /^(AUTHORS|LICENSE|COPYING|CHANGELOG|README|NOTICE|CONTRIBUTING|GOVERNANCE|Makefile|\.npmignore|\.gitignore|\.eslintrc|\.editorconfig)(\.[^.]+)?$/;

// Scanner scripts contain the token patterns themselves — skip them to
// avoid self-matches. Future maintainers: add any new scanner files here.
// `_load_private_tokens.js` joined the list with #R5 because its JSDoc
// references the HARD-RULE patterns (`CLAUDE.md / .claude*`) literally,
// which would otherwise trip ATTRIBUTION_LEAK_RE.
var SELF_EXCLUDE = {
    'script/check_no_local_leak.js':  true,
    'script/prepare_version.js':      true,
    'script/_load_private_tokens.js': true
};
// Files larger than this are skipped — production binaries and bundles
// don't warrant a byte-by-byte scan.
var MAX_SCAN_BYTES = 2 * 1024 * 1024;

function isTextPath(p) {
    if (TEXT_EXT.test(p)) return true;
    var base = p.split('/').pop();
    if (TEXT_BASENAME.test(base)) return true;
    return false;
}

function scanContent(filePath) {
    var stat;
    try { stat = fs.statSync(filePath); } catch (e) { return []; }
    if (!stat.isFile() || stat.size > MAX_SCAN_BYTES) return [];

    var content;
    try { content = fs.readFileSync(filePath, 'utf8'); } catch (e) { return []; }

    var hits = [];
    for (var i = 0; i < CONTENT_TOKENS.length; i++) {
        if (CONTENT_TOKENS[i].allowIn && CONTENT_TOKENS[i].allowIn.test(filePath)) continue;
        if (CONTENT_TOKENS[i].pattern.test(content)) {
            hits.push(CONTENT_TOKENS[i].name);
        }
    }

    // AI-attribution leak (#R5). Strip vendor-functionality references
    // from a one-shot copy of the content so legitimate AI-connector
    // code and provider tables don't false-positive; then test the
    // remaining content against ATTRIBUTION_LEAK_RE. Single boolean
    // hit — caller surfaces the offending path + the marker.
    var stripped = content.replace(ATTRIBUTION_EXCEPTION_RE, '');
    if (ATTRIBUTION_LEAK_RE.test(stripped)) {
        hits.push('AI-attribution leak');
    }
    return hits;
}

// Stable-publish gate (§92 follow-up (a)). Fires BEFORE the scan starts.
// `npm publish` without `--tag alpha` (i.e. tag=latest) requires the
// maintainer-local sidecar to be present; otherwise the content-level
// scan would be silently disabled, and the publish could ship leaked
// tokens. Alpha publish, npm pack, and contributor flows are unaffected
// — path-level scanning still runs in those cases.
var sidecarPath = path.join(__dirname, '.private-tokens.json');
if (
    process.env.npm_command === 'publish'
    && (process.env.npm_config_tag === 'latest' || !process.env.npm_config_tag)
    && !fs.existsSync(sidecarPath)
) {
    console.error('[prepack] STABLE PUBLISH BLOCKED: ' + sidecarPath + ' missing.');
    console.error('[prepack] The maintainer-local sidecar is required for stable publish.');
    console.error('[prepack] Recreate from a personal backup outside the repo, or rebuild');
    console.error('[prepack] from the schema documented in script/_load_private_tokens.js.');
    console.error('[prepack] (Alpha publish, npm pack, and contributor flows are not affected.)');
    process.exit(1);
}

try {
    var raw = execSync('npm pack --dry-run --json --ignore-scripts', {
        stdio: ['ignore', 'pipe', 'pipe']
    }).toString();

    var parsed = JSON.parse(raw);
    var pathMatches = [];
    var contentMatches = [];

    // npm <= 11 emits an ARRAY of pack entries; npm 12 emits an OBJECT keyed
    // by package name (pack/publish JSON output synchronized in npm 12).
    // Normalize both to an entries array — and fail CLOSED below when zero
    // files were recognized: an unknown output shape must block the publish,
    // never vacuously pass (under npm 12 the old array-indexed loop iterated
    // zero times and reported a clean pack without scanning anything).
    var entries = Array.isArray(parsed)
        ? parsed
        : ( (parsed && typeof parsed === 'object')
            ? Object.keys(parsed).map(function(k) { return parsed[k]; })
            : [] );
    var totalFiles = 0;

    for (var i = 0; i < entries.length; i++) {
        var files = entries[i].files || [];
        totalFiles += files.length;
        for (var j = 0; j < files.length; j++) {
            var p = files[j].path;

            if (PATH_PATTERN.test(p)) {
                pathMatches.push(p);
            }

            if (isTextPath(p) && !SELF_EXCLUDE[p]) {
                var hits = scanContent(p);
                for (var k = 0; k < hits.length; k++) {
                    contentMatches.push(p + ' — ' + hits[k]);
                }
            }
        }
    }

    if (totalFiles === 0) {
        console.error('[prepack] ERROR: unrecognized `npm pack --json` output shape — zero files scanned.');
        console.error('[prepack] Failing closed — the leak scan must never pass without scanning the pack listing.');
        process.exit(1);
    }

    var failed = false;

    if (pathMatches.length > 0) {
        console.error('[prepack] ERROR: local-tool paths in pack listing:');
        for (var a = 0; a < pathMatches.length; a++) {
            console.error('  - ' + pathMatches[a]);
        }
        console.error('[prepack] Fix .npmignore (or package.json "files") before publishing.');
        failed = true;
    }

    if (contentMatches.length > 0) {
        if (failed) console.error('');
        console.error('[prepack] ERROR: Leaks in pack contents:');
        for (var b = 0; b < contentMatches.length; b++) {
            console.error('  - ' + contentMatches[b]);
        }
        console.error('[prepack] Scrub these files before publishing.');
        failed = true;
    }

    if (failed) {
        process.exit(1);
    }

    console.log('[prepack] OK: pack listing and contents are clean.');
    process.exit(0);
} catch (err) {
    console.error('[prepack] Check failed: ' + (err.message || err));
    console.error('[prepack] Failing closed — investigate before publishing.');
    process.exit(1);
}
