/**
 * Gina — DTO types for bundle `fixture`
 *
 * AUTO-GENERATED by `gina bundle:types fixture @<project>` — do not edit by hand.
 * Source of truth: the DTO factories in `dtos/`.
 * Re-run after adding, removing or changing a DTO.
 *
 * Each DTO emits TWO types, because a DTO's declared shape and the shape the server
 * actually holds are not the same:
 *
 *   <Name>           the DECLARED shape — what the client sends, and what the OpenAPI /
 *                    MCP schema documents. Includes the excluded fields.
 *   <Name>Projected  what the SERVER holds — `req.dto` after the validation pipe, and
 *                    the body a `param.responseDto` puts on the wire. Excluded fields
 *                    are dropped.
 *
 * Note: a `date` field is typed `string`, not `Date` — the validator coerces it to an
 * ISO string. And `@minimum` / `@maximum` ride in the JSON Schema for OpenAPI fidelity
 * but are NOT enforced at runtime in this cut.
 */

/**
 * `CreateUser` — the DECLARED shape: what the client sends, and what the OpenAPI /
 * MCP schema documents. Includes the excluded field the server strips.
 */
export interface CreateUser {
    /**
     * The account email.
     * @format email
     */
    email: string;

    /**
     * @minimum 0 (schema-only — not enforced at runtime)
     * @maximum 120 (schema-only — not enforced at runtime)
     */
    age?: number;
    active?: boolean;
    role: "admin" | "editor" | "viewer";

    /** @format date */
    joinedOn?: string;

    /**
     * @minLength 2
     * @maxLength 24
     */
    nickname?: string;

    /**
     * Accepted and validated, then stripped.
     * @remarks Excluded — stripped from the validated payload and never serialised.
     */
    token: string;
}

/**
 * `CreateUser` as the SERVER holds it — `req.dto` after the validation pipe, and the
 * body a `param.responseDto` puts on the wire.
 *
 * The excluded field is dropped: `token`.
 */
export type CreateUserProjected = Omit<CreateUser, "token">;

/**
 * `Ping` — the DECLARED shape: what the client sends, and what the OpenAPI /
 * MCP schema documents.
 */
export interface Ping {
    nonce: string;
}

/**
 * `Ping` as the SERVER holds it — `req.dto` after the validation pipe, and the
 * body a `param.responseDto` puts on the wire.
 *
 * This DTO excludes no field, so the projection is the declared shape.
 */
export type PingProjected = Ping;

/**
 * `PriceTier` — the DECLARED shape: what the client sends, and what the OpenAPI /
 * MCP schema documents.
 */
export interface PriceTier {
    tier: "$ 10" | "$ 25" | "$ 50";

    /** @minimum 0 (schema-only — not enforced at runtime) */
    amount?: number;
}

/**
 * `PriceTier` as the SERVER holds it — `req.dto` after the validation pipe, and the
 * body a `param.responseDto` puts on the wire.
 *
 * This DTO excludes no field, so the projection is the declared shape.
 */
export type PriceTierProjected = PriceTier;

/**
 * `SearchQuery` — the DECLARED shape: what the client sends, and what the OpenAPI /
 * MCP schema documents.
 */
export interface SearchQuery {
    /**
     * @minLength 1
     * @maxLength 128
     */
    q: string;

    /**
     * @minimum 1 (schema-only — not enforced at runtime)
     * @maximum 100 (schema-only — not enforced at runtime)
     */
    "page-size"?: number;
    sort?: "asc" | "desc";
    limit?: 10 | 25 | 50;
    exact?: true | false;

    /** @pattern ^[a-z0-9-]+$ */
    slug?: string;

    /** The DTO is `.passthrough()` — undeclared keys are kept. */
    [key: string]: any;
}

/**
 * `SearchQuery` as the SERVER holds it — `req.dto` after the validation pipe, and the
 * body a `param.responseDto` puts on the wire.
 *
 * This DTO excludes no field, so the projection is the declared shape.
 */
export type SearchQueryProjected = SearchQuery;

/**
 * A user, as the API returns it
 *
 * The password hash is declared so the shape is honest, and excluded so it cannot leave the process.
 *
 * `UserView` — the DECLARED shape: what the client sends, and what the OpenAPI /
 * MCP schema documents. Includes the excluded field the server strips.
 */
export interface UserView {
    id?: number;

    /** @format email */
    email?: string;
    role?: "admin" | "editor" | "viewer";

    /**
     * Never serialised.
     * @remarks Excluded — stripped from the validated payload and never serialised.
     */
    passwordHash?: string;
}

/**
 * `UserView` as the SERVER holds it — `req.dto` after the validation pipe, and the
 * body a `param.responseDto` puts on the wire.
 *
 * The excluded field is dropped: `passwordHash`.
 */
export type UserViewProjected = Omit<UserView, "passwordHash">;
