.TH "GEENA\-FRAMEWORK" "1" "March 2014" "" ""
.SH "NAME"
\fBgeena-framework\fR \- Framework cli
.SH SYNOPSIS
.P
\fBgeena framework\fR [ \fBoption\fR ]
.P
\fBgeena framework\fR:[ \fBtask\fR ] [ \fBservice\fR | \fBarguments\fR ]
.P
\fBgeena framework\fR:[ \fBtask\fR ] [ \fBservice\fR] [ \fBarguments\fR ]
.SH DESCRIPTION
.P
\fBgeena framework\fR alows you to perform tasks on the framework and its services\.
.SH OPTIONS
.P
\fB\-t\fR, \fB\-\-status\fR        Get status of the framework\.
.P
\fB\-h\fR, \fB\-\-help\fR Prints help for \fBgeena framework\fR command\.
.SH TASKS
.P
\fB\-s\fR, \fBstart\fR
        Starts the framework\.
.P
\fB\-k\fR, \fBstop\fR | \fBkill\fR
        Stops the framework\.
.P
\fB\-r\fR, \fBrestart\fR
        Restarts the framework\.
.P
\fB\-u\fR, \fBupdate\fR
        Get status of the framework\.
.P
\fBset\fR
        Set environment variables
.SH ENVIRONMENT ARGUMENTS
.P
\fB\-\-version=val\fR
        Tells Geena to run services with a specific framework version\. 
.P
e\.g\. Start Geena using v0\.1\.5 of the framework
.P
.RS 2
.EX
$ geena framework:start \-\-version=0\.1\.5
.EE
.RE
.QP
.P
N\.B\.: This will override default settings\. See \fBgeena\-set\fR manpage\.

.
.P
\fB\-\-env=val\fR
        Tells Geena to run services with a specific framework environment\.
.P
e\.g\. Runs the framework with development environment
.P
.RS 2
.EX
$ geena framework:start \-\-env=dev
.EE
.RE
.P
\fB\-\-node\-version=val\fR
        It is the \fBNode\.js\fR version, the binary used by Geena\.
        More than one version at the time can be used\.
.SH EXEMPLE
.P
\fBgeena\fR\'s command line only works if the framework is started\.
You can start the framwork this way
.P
.RS 2
.EX
$ geena framework:start
.EE
.RE
.P
or by using the alias
.P
.RS 2
.EX
$ geena start
.EE
.RE
.SH AUTHOR
.P
Martin\-Luther ETOUMAN was the original Author of \fBgeena\fR\|\. Stephane HEAV joined the project since version 0\.1\.0\.
.SH COPYRIGHT
.P
Copyright (c) 2009\-{year} Rhinostone geena@rhinostone\.com
.SH SEE ALSO
.P
\fBgeena\fR(1), \fBgeena\-project\fR(1), \fBgeena\-bundle\fR(1), \fBgeena:model\fR(1)
.SH COLOPHON
.P
This page is part of release {version} of the \fBgeena\fR project\. A description of the project,
and informations about reporting bugs can be found on the official web site:  \fIhttp://www\.geenajs\.com\fR
.P
The project is also on GitHub:  \fIhttps://github\.com/rhinostone/geena\fR
.P
Here is the mailling list:  \fIhttps://groups\.google\.com/forum/#!forum/geenajs\fR

