.TH "GEENA" "1" "March 2014" "" ""
.SH "NAME"
\fBgeena\fR \- Command line interface
.SH NAME
.P
\fBgeena\fR
.SH SYNOPSIS
.P
\fBgeena\fR    [ \fB\-v\fR | \fB\-h\fR] [ \fB\-\-debug\-brk\fR ]
         [ \fBassetic\fR:\fBtask\fR] [\fBarguments\fR]
.SH DESCRIPTION
.P
Geena is a MVC & Events Driven Framework that allows you to create\. 
.SH OPTIONS
.P
\fB\-v\fR, \fB\-\-version\fR            Prints current framework version\.
.P
\fB\-h\fR, \fB\-\-help\fR               Prints\.
.SH ENVIRONMENT
.P
\fBversion\fR
        It is the default framework \fBversion\fR used by Geena\.
.P
\fBenv\fR
        It is the runtime environment\.
.P
\fBnode\fR
        It is the \fBNode\.js\fR version, the binary used by Geena\.
        More than one version at the time can be used\.
.SH EXEMPLE
.P
\fBgeena\fR\'s command line only works if the framework is started\.
You can start the framwork this way
.P
.RS 2
.EX
$ geena framework:start
.EE
.RE
.P
or by using the alias
.P
.RS 2
.EX
$ geena start
.EE
.RE
.SH AUTHOR
.P
Martin\-Luther ETOUMAN was the original Author of \fBgeena\fR\|\. Stephane HEAV joined the project since version 0\.1\.0\.
.SH COPYRIGHT
.P
Copyright (c) 2009\-{year} Rhinostone geena@rhinostone\.com
.SH SEE ALSO
.P
\fBgeena:framework\fR(1), \fBgeena:project\fR(1), \fBgeena:bundle\fR(1), \fBgeena:service\fR(1), \fBgeena:model\fR(1)
.SH COLOPHON
.P
This page is part of release {version} of the \fBgeena\fR project\. A description of the project,
and informations about reporting bugs can be found on the official web site:  \fIhttp://www\.geenajs\.com\fR
.P
The project is also on GitHub:  \fIhttps://github\.com/rhinostone/geena\fR
.P
Here is the mailling list:  \fIhttps://groups\.google\.com/forum/#!forum/geenajs\fR

